//
//  TopicsManager.swift
//  LearnSwift
//
//  Created by Куат Оралбеков on 25.09.2023.
//

import Foundation

class TopicsManager {
    
    private init() {}
    
    static let shared = TopicsManager()
    
    func get() -> [Topic] {
        var topics = [Topic]()
        let topic1 = Topic(number: "1", name: "Introduction", description: "Introductory information about the language", isPassed: UserDefaults.standard.bool(forKey: "topic1"), text: "Swift is a new programming language for developing applications for iOS, macOS, watchOS and tvOS. Despite this, many parts of Swift may be familiar to you from your experience of developing in C and Objective-C. Swift provides its own versions of the fundamental C and Objective-C types, including Int for integers, Double and Float for floating-point values, Bool for Boolean values, String for text. Swift also provides powerful versions of the three main collection types, Array, Set, and Dictionary, as described in the Collection Types section. Like C, Swift uses variables to store and access values by a unique name. Swift also makes extensive use of variables whose values cannot be changed. They are known as constants, and are much more powerful than constants in C. Constants are used everywhere in Swift to make the code safer and cleaner in cases where you are working with values that should not change. In addition to the familiar types, Swift includes extended types that are not present in Objective-C. These include tuples that allow you to create and pass groups of values. Tuples can return multiple values from a function as a single integer value. Swift also includes optional types that allow you to work with missing values. Optional values say either 'there is a value here, and it is equal to x', or 'there is no value at all'. Optional types are similar to using nil with pointers in Objective-C, but they work with all types, not just classes. Optional values are safer and more expressive than nil pointers in Objective-C, and are at the heart of many of Swift's most powerful features. Swift is a type-safe language, which means Swift helps you understand what types of values your code can work with. If a piece of your code expects a String, type security will prevent you from passing it an Int by mistake. In addition, type safety will prevent you from accidentally passing an optional String to a piece of code that expects a non-optional String. Type safety allows you to catch and fix bugs as early as possible in the development process. I hope you find these variations helpful in choosing the perfect name for your premium watch shop!",
                           questions: [Question(text: "", answers: [Answer(text: "", isCorrect: true)])], practice: nil)
        topics.append(topic1)
        let topic2 = Topic(number: "2", name: "Constants and variables", description: "Learn about constants and variables", isPassed: UserDefaults.standard.bool(forKey: "topic2"), text: "Constants and variables must be declared before they can be used. Constants are declared using the let keyword, and variables are declared using var. Here is an example of how constants and variables can be used to track the number of login attempts that a user has made: \nlet maximum Number Of Login Attempts = 10\nvar current Login Attempt = 0\nThis code can be read as: \n'Declare a new constant named maximumNumberOfLoginAttempts, and set it to 10. Then, declare a new variable named currentLoginAttempt, and set its initial value to 0.'\nIn this example, the maximum number of available login attempts is declared as a constant, because the maximum value never changes. The counter of the current number of login attempts is declared as a variable, because this value should increase after each failed login attempt.You can declare multiple constants or multiple variables on the same line, separating them with commas: var x = 0.0, y = 0.0, z = 0.0"
                           , questions: [Question](), practice: CodePractice(text: "Declare constant with name number with value 10.", initialCode: "", correctCode: "let number = 10"))
        topics.append(topic2)
        
        let topic3 = Topic(number: "3", name: "Annotation of types", description: "You can add a type designation when declaring a constant or variable", isPassed: UserDefaults.standard.bool(forKey: "topic3"), text: "You can add a type designation when declaring a constant or variable to have a clear idea of the types of values that constants or variables can store. You can write a type designation by placing a colon after the name of a constant or variable, then a space followed by the name of the type used.\nThis example adds a type designation for a variable named welcome Message to indicate that the variable can store a String:\nvar welcomeMessage: String\nThe colon in the declaration means '...of type...', so the code above can be read as:\n'Declare a variable named welcomeMessage, whose type will be String'\nThe phrase 'whose type will be String' means 'can store any String value'. Imagine that the phrase 'the type of which will be such and such' means - the value that will be stored.\nNow the variable welcomeMessage can be assigned any text value, without any errors:\nwelcomeMessage = \"Hello\"\nYou can create multiple variables of the same type in one comma-separated line with one type annotation after the last variable name.:\nvar red, green, blue: Double", questions: [Question](), practice: CodePractice(text: "Declare constant with name number with value 10 of type Int", initialCode: "", correctCode: "let number: Int = 10"))
        topics.append(topic3)
        
        let topic4 = Topic(number: "4", name: "Annotation of types", description: "You can add a type designation when declaring a constant or variable", isPassed: UserDefaults.standard.bool(forKey: "topic3"), text: "You can add a type designation when declaring a constant or variable to have a clear idea of the types of values that constants or variables can store. You can write a type designation by placing a colon after the name of a constant or variable, then a space followed by the name of the type used.\nThis example adds a type designation for a variable named welcome Message to indicate that the variable can store a String:\nvar welcomeMessage: String\nThe colon in the declaration means '...of type...', so the code above can be read as:\n'Declare a variable named welcomeMessage, whose type will be String'\nThe phrase 'whose type will be String' means 'can store any String value'. Imagine that the phrase 'the type of which will be such and such' means - the value that will be stored.\nNow the variable welcomeMessage can be assigned any text value, without any errors:\nwelcomeMessage = \"Hello\"\nYou can create multiple variables of the same type in one comma-separated line with one type annotation after the last variable name.:\nvar red, green, blue: Double", questions: [Question](), practice: CodePractice(text: "Declare constant with name number with value 10 of type Int", initialCode: "", correctCode: "let number: Int = 10"))
        topics.append(topic4)
        
        
        return topics
    }
    
}
